import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Amanak ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar">
      <body
        className={`${cairo.variable}  antialiased`} dir="rtl"
      >
        <main className="py-10">{children}</main>

      </body>
    </html>
  );
}
